#:schema node_modules/wrangler/config-schema.json
name = "react-with-hono"
compatibility_date = "2024-09-27"
main = "./dist/index.js"

[assets]
directory = "./dist/assets"
binding = "ASSETS"
not_found_handling = "single-page-application"
